export const dayPhotoActionTypes = {
    GET_PHOTO_OF_THE_DAY_START: 'GET_PHOTO_OF_THE_DAY_START',
    GET_PHOTO_OF_THE_DAY_SUCCESS: 'GET_PHOTO_OF_THE_DAY_SUCCESS',
    GET_PHOTO_OF_THE_DAY_FAILURE: 'GET_PHOTO_OF_THE_DAY_FAILURE', 
}