export const breakdownActionTypes = {
    GET_BREAKDOWN_ARTICLES_START: 'GET_BREAKDOWN_ARTICLES_START',
    GET_BREAKDOWN_ARTICLES_SUCCESS: 'GET_BREAKDOWN_ARTICLES_SUCCESS',
    GET_BREAKDOWN_ARTICLES_FAILURE: 'GET_BREAKDOWN_ARTICLES_FAILURE',
}